# Generated by Django 5.2.4 on 2025-10-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('stock', models.IntegerField(verbose_name='สต็อก')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะสินค้า')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.TextField(verbose_name='ที่อยู่จัดส่ง')),
                ('status', models.CharField(choices=[('PENDING', 'รอการยืนยัน'), ('CONFIRMED', 'ยืนยันแล้ว/รอชำระเงิน'), ('PAID', 'ชำระเงินแล้ว/กำลังจัดส่ง'), ('SHIPPED', 'จัดส่งแล้ว'), ('DELIVERED', 'จัดส่งสำเร็จ'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=50, verbose_name='สถานะคำสั่งซื้อ')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขพัสดุ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งซื้อ')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50, verbose_name='วิธีการชำระเงิน')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสทำธุรกรรม')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดชำระ')),
                ('is_successful', models.BooleanField(default=False, verbose_name='สถานะชำระเงิน')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='คำสั่งซื้อ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วยตอนสั่งซื้อ')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='สินค้า')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวน')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='ตะกร้า')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='สินค้า')),
            ],
        ),
    ]
