# Generated by Django 5.2.4 on 2025-10-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='ตะกร้า'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอการชำระเงิน'), ('CONFIRMED', 'ยืนยันคำสั่งซื้อ/รอดำเนินการ'), ('SHIPPED', 'กำลังจัดส่ง'), ('DELIVERED', 'จัดส่งสำเร็จ'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=50, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ยอดรวมทั้งหมด'),
        ),
    ]
